apiVersion: v1
kind: Deployment
metadata:
  name: "guestbook-deployment"
	labels:
		app: "guestbook"
spec:
	replicas: 1
	selector:
		matchLabels:
			app: "guestbook"
	template:
		metadata:
			labels:
				app: "guestbook"
		spec:
			containers:
			- name: guestbook
			  image: anycmon/guestbook
        ports:
        - containerPort: 3001
	
